spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local_db
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect  # Hibernate가 MySQL을 인식할 수 있도록 추가
    hibernate:
      ddl-auto: update
    show-sql: true